server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  #eureka服务端实例名称
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #false 表示自己端就是注册中心，不用检索服务，职责就是维护服务实例
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
