server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url:
    username: root
    password:

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jarvis.springcloud.entities